In [ ]:
%reset -f
import matplotlib.pyplot as plt
import os
import numpy as np
import parsing
import copy
import vertex
import time
import movement
import cell
import geometry
import data_holder
%load_ext autoreload
%autoreload 2
%reload_ext autoreload
%matplotlib inline

: 

In [109]:
data = parsing.read_data(
    os.path.join("data", "network_vertices.txt"),
    os.path.join("data", "cell_indices.txt"), 
    5, 5, 1, 1, 0.01
)

In [110]:
data.vert_list

[V(0.930866, 0.271744),
 V(0.116862, 0.802272),
 V(0.563237, 1.233827),
 V(0.349978, 1.81711),
 V(0.375702, 2.313142),
 V(0.604067, 2.999615),
 V(0.299085, 3.474244),
 V(-0.064818, 4.652581),
 V(1.398975, -0.074888),
 V(1.391676, 1.049655),
 V(1.160173, 1.56442),
 V(1.60824, 1.961066),
 V(1.342551, 2.416602),
 V(1.562803, 3.106261),
 V(1.064323, 3.488212),
 V(1.391571, 3.776807),
 V(2.141749, 0.281557),
 V(2.448764, 1.04931),
 V(2.586193, 1.480577),
 V(2.184154, 1.890135),
 V(2.543788, 2.569701),
 V(1.866666, 2.730649),
 V(2.487271, 3.514713),
 V(1.770058, 3.801211),
 V(3.06361, 0.284279),
 V(3.555957, 0.889567),
 V(2.773178, 1.238788),
 V(3.222748, 1.948208),
 V(3.511009, 2.742986),
 V(3.469543, 2.862983),
 V(3.386142, 3.557367),
 V(3.241826, 4.298552),
 V(4.18583, 0.387196),
 V(4.197804, 0.781788),
 V(3.907473, 1.217865),
 V(4.145059, 2.032152),
 V(4.437937, 2.698011),
 V(3.992574, 3.148598),
 V(4.143524, 3.371457),
 V(4.134823, 4.58872),
 V(4.703293, 0.511607),
 V(5.243425, 0.469836

In [106]:
movement.move_vertices(data.vert_list, data)

In [107]:
data.vert_list

[V(1.0488479617579762, 0.3944357306644693),
 V(4.8487382395433976, 0.9118290968782355),
 V(0.5588822541306485, 1.1459874999523887),
 V(0.36071155784116904, 1.8835032976879265),
 V(0.19657022631100182, 2.2933992165093153),
 V(0.803339575286694, 2.933782476053119),
 V(0.09013378817781528, 3.436260643611808),
 V(4.8022769369878056, 0.20421382911955277),
 V(1.5409873384980437, 4.849693042307328),
 V(1.2740929809387729, 1.1162360269573655),
 V(1.131172856573671, 1.6793916259800992),
 V(1.6443406365746422, 1.9530499579432954),
 V(1.3777163968706887, 2.410071536955316),
 V(1.6375929493645889, 3.2513375738167127),
 V(1.0131571403523516, 3.463395616806532),
 V(1.3718914371953648, 4.092623139987279),
 V(1.948635091919701, 0.3429600655422854),
 V(2.6514629016968723, 1.0962918369428878),
 V(2.6352033527242544, 1.6232647155056377),
 V(2.147701333912363, 1.8538731161580446),
 V(2.5916583139700524, 2.630989302378541),
 V(1.7198391062785525, 2.558962877158864),
 V(2.537730998499639, 3.538125183789174)

In [26]:
geometry.midpoint_formula([1, 1], [2, 2])

[1.5, 1.5]

In [85]:
movement.move_vertices(data.vert_list, data)

[11.79819618 12.26917307]


In [35]:
geometry.midpoint_formula_boundary_check([1, 2], [2,2], data)

array([1.5, 2. ])

In [36]:
vector = np.array([1, 2])

In [64]:
v1 = vertex.Vertex(0, 0)
v2 = vertex.Vertex(2, 0)
v3 = vertex.Vertex(4, 0)
v4 = vertex.Vertex(2, 2)
v5 = vertex.Vertex(0, 2)
v6 = vertex.Vertex(3, 3)
v7 = vertex.Vertex(2, 4.9)
cell1_list = [
    v1, v2, v4, v5
]
cell2_list = [
    v2, v4, v6, v3
]
cell3_list = [
    v5, v7, v6, v4
]
cell1 = cell.Cell(cell1_list, data)
cell2 = cell.Cell(cell2_list, data)
cell3 = cell.Cell(cell3_list, data)

In [65]:
geometry.find_shared_edge(cell1, cell2, v2)

(V(2, 0), V(2, 2))

In [66]:
cell1.center

array([1., 1.])

In [69]:
cell1.center = [-1, -1]
cell2.center = [3, 3]
geometry.midpoint_formula_boundary_check(cell1.center, cell2.center, data)

array([3.5, 3.5])

4

In [71]:
e = np.zeros(2)
e[0] = 1

array([1., 0.])